version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: websocket_server
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
